import { BirdConfig, BirdId, LootItemConfig, LootType } from '../types/game';

export const BIRD_CONFIGS: Record<BirdId, BirdConfig> = {
  crow: {
    id: 'crow',
    name: '闪光鸦 (Corvus)',
    nameEn: 'Crown Crow',
    townTheme: '童话欧洲小镇',
    townThemeEn: 'Fairy-tale Naif Town',
    baseWeight: 1.2,
    maxWeight: 9.5,
    glideFactor: 1.15,
    description: '头戴金色微冠的怪盗黑鸦，尤其钟爱金币、银勺和璀璨珠宝，脖子上可串戴整套首饰！',
    color: '#1e293b',
    accentColor: '#fbbf24',
    beakColor: '#f59e0b',
    eyeColor: '#ffffff',
    specialTrait: '对闪亮宝物感知范围+25%，金币收益额外提升',
  },
  pigeon: {
    id: 'pigeon',
    name: '咕咕鸽 (Pidge)',
    nameEn: 'Bakery Pigeon',
    townTheme: '巴黎经典烘焙街区',
    townThemeEn: 'Parisian Boulevard',
    baseWeight: 1.0,
    maxWeight: 8.5,
    glideFactor: 1.05,
    description: '徘徊在法式咖啡店与面包房的常客，最擅长在顾客喝咖啡的一瞬间叼走整个可颂！',
    color: '#64748b',
    accentColor: '#f43f5e',
    beakColor: '#fb923c',
    eyeColor: '#fee2e2',
    specialTrait: '食用可颂和法棍时体力回复双倍，并获得长时间滑翔气流',
  },
  seagull: {
    id: 'seagull',
    name: '暴风鸥 (Gull)',
    nameEn: 'Harbor Gull',
    townTheme: '蔚蓝海滨度假城',
    townThemeEn: 'Riviera Harbor',
    baseWeight: 1.4,
    maxWeight: 11.0,
    glideFactor: 1.25,
    description: '海滩上的无敌霸主，下潜破空速度极快，拥有惊人的空气动力学升力！',
    color: '#f8fafc',
    accentColor: '#38bdf8',
    beakColor: '#eab308',
    eyeColor: '#0f172a',
    specialTrait: '极速俯冲初速度+20%，贴地掠水激起加速飞浪',
  },
  cockatoo: {
    id: 'cockatoo',
    name: '葵花葵 (Crest)',
    nameEn: 'Punk Cockatoo',
    townTheme: '阳光小镇狂欢街',
    townThemeEn: 'Sunny Outback Village',
    baseWeight: 1.3,
    maxWeight: 10.0,
    glideFactor: 1.1,
    description: '头顶鲜黄朋克羽冠的恶作剧大师，能撞开小障碍并惊扰NPC爆出更多闪光物！',
    color: '#f1f5f9',
    accentColor: '#facc15',
    beakColor: '#475569',
    eyeColor: '#3b82f6',
    specialTrait: '抗撞击韧性+40%，眩晕恢复时间减半',
  },
};

export const LOOT_CONFIGS: Record<LootType, LootItemConfig> = {
  copper_coin: {
    type: 'copper_coin',
    name: '石板路铜币',
    points: 15,
    weight: 0.25,
    color: '#b45309',
    sparkleColor: '#fde047',
    icon: '🪙',
    category: 'shiny',
    description: '行人从口袋不慎滑落在石板缝隙间的古铜币。',
    contextHint: '石板路边缝隙',
  },
  gold_coin: {
    type: 'gold_coin',
    name: '自行车旁的金币',
    points: 60,
    weight: 0.65,
    color: '#eab308',
    sparkleColor: '#fef08a',
    icon: '🟡',
    category: 'shiny',
    description: '靠在路灯旁的复古自行车脚踏板下掉落的金币！',
    contextHint: '自行车旁地砖',
  },
  silver_spoon: {
    type: 'silver_spoon',
    name: '咖啡桌银茶匙',
    points: 90,
    weight: 0.75,
    color: '#cbd5e1',
    sparkleColor: '#ffffff',
    icon: '🥄',
    category: 'shiny',
    description: '露天咖啡馆红白格桌布上，顾客留在意式浓缩咖啡杯旁的纯银茶匙！',
    contextHint: '露天咖啡桌',
  },
  silver_fork: {
    type: 'silver_fork',
    name: '野餐垫银餐叉',
    points: 95,
    weight: 0.8,
    color: '#e2e8f0',
    sparkleColor: '#ffffff',
    icon: '🍴',
    category: 'shiny',
    description: '草地上黄色格子野餐垫旁，野餐家庭遗留的闪光小银叉。',
    contextHint: '草坪野餐垫',
  },
  reading_glasses: {
    type: 'reading_glasses',
    name: '爷爷的反光老花镜',
    points: 110,
    weight: 0.5,
    color: '#ca8a04',
    sparkleColor: '#fde68a',
    icon: '👓',
    category: 'shiny',
    description: '长椅上打瞌睡的老爷爷放在报纸上的金丝边老花镜，镜片闪烁反光！',
    contextHint: '公园长椅报纸上',
  },
  vintage_key: {
    type: 'vintage_key',
    name: '喷泉沿老铜钥匙',
    points: 130,
    weight: 1.0,
    color: '#d97706',
    sparkleColor: '#fde68a',
    icon: '🗝️',
    category: 'shiny',
    description: '遗忘在古镇中央喷泉雕花石台上的大门铜钥匙。',
    contextHint: '喷泉石沿台面',
  },
  pocket_watch: {
    type: 'pocket_watch',
    name: '长椅上的金怀表',
    points: 220,
    weight: 1.4,
    color: '#ca8a04',
    sparkleColor: '#fef9c3',
    icon: '⏱️',
    category: 'shiny',
    description: '散步绅士搭在长椅靠背外套里垂落的精致罗马字金怀表！',
    contextHint: '长椅外套上',
  },
  sparkle_gem: {
    type: 'sparkle_gem',
    name: '二楼阳台宝石戒指',
    points: 320,
    weight: 1.6,
    color: '#38bdf8',
    sparkleColor: '#bae6fd',
    icon: '💎',
    category: 'shiny',
    description: '二楼开窗花盆旁边，晒太阳贵妇摘下暂搁在窗沿的璀璨蓝宝戒指！',
    contextHint: '二楼阳台窗沿',
  },
  gold_brooch: {
    type: 'gold_brooch',
    name: '花圃边的蝴蝶胸针',
    points: 180,
    weight: 1.1,
    color: '#facc15',
    sparkleColor: '#fef08a',
    icon: '✨',
    category: 'shiny',
    description: '掉在花圃矮木桩旁的镀金镂空蝴蝶胸针。',
    contextHint: '花园木桩矮栅',
  },
  croissant: {
    type: 'croissant',
    name: '面包房刚出炉羊角包',
    points: 45,
    weight: 0.35,
    color: '#d97706',
    sparkleColor: '#fed7aa',
    icon: '🥐',
    category: 'food',
    description: '法式烘焙店外木托盘上刚出炉的金黄香脆黄油可颂，香气扑鼻！',
    contextHint: '面包房展示窗',
  },
  potion_bottle: {
    type: 'potion_bottle',
    name: '桌边的冰镇汽水',
    points: 80,
    weight: 0.5,
    color: '#ec4899',
    sparkleColor: '#fbcfe8',
    icon: '🥤',
    category: 'buff',
    description: '咖啡馆遮阳伞下未开封的闪光粉红苏打汽水，喝下极速冲刺！',
    contextHint: '遮阳伞咖啡座',
  },
  red_apple: {
    type: 'red_apple',
    name: '树下掉落的红苹果',
    points: 35,
    weight: 0.35,
    color: '#ef4444',
    sparkleColor: '#fca5a5',
    icon: '🍎',
    category: 'food',
    description: '庭院苹果树下滚落在青草丛里的一颗鲜红甜苹果。',
    contextHint: '果树草地上',
  },
  fountain_sip: {
    type: 'fountain_sip',
    name: '喷泉清洌泉水',
    points: 50,
    weight: 0,
    color: '#38bdf8',
    sparkleColor: '#e0f2fe',
    icon: '💧',
    category: 'sip',
    description: '俯冲贴水轻饮喷泉池中的甘甜泉水，精神抖擞，获得顺风滑翔！',
    contextHint: '中央喷泉水池',
  },
};

// Physics Tuning Constants
export const GAME_PHYSICS = {
  // Top 30% is cruising altitude zone
  CRUISE_RATIO: 0.22,
  CRUISE_SPEED_BASE: 4.8,
  
  // Parabolic drag & dive multipliers
  DRAG_FORCE_SCALE: 0.08,
  MAX_DRAG_DISTANCE: 180,
  MIN_DRAG_DISTANCE: 25,
  
  // Physics tick
  GRAVITY: 0.26,
  SPRING_BUOYANCY_FACTOR: 0.00062, // restores bird back up smoothly as depth increases
  AIR_DRAG: 0.988,
  LIFT_RECOVERY_RATE: 0.045,
  
  // Collision
  BIRD_RADIUS: 24,
  LOOT_COLLECT_RADIUS: 36,
  
  // Balloon pack
  BALLOON_DURATION_SEC: 2.2,
  BALLOON_SLOW_FACTOR: 0.35,
  
  // Weight boundaries
  LIGHT_WEIGHT_LIMIT: 3.0,
  HEAVY_WEIGHT_LIMIT: 6.5,
};
